services:
  test:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: pytest tests/ -v 
  
  build:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: python -m bot