version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      LOG_CHANNEL_ID: ${TEST_LOG_CHANNEL_ID}
    volumes:
      - .:/app
    command: pytest tests/ -v 